export default {
  notFound: 'Not Found',
  routes: {
    common: {
      edit: 'Edit {name}',
      add: 'Add {name}',
    },
    '/dashboard': 'Dashboard',
    '/backstage': 'Backstage',
    '/admin/index': 'Admins',
    '/route/index': 'Routes',
    '/role/index': 'Roles',
    '/admin': 'Admin',
    '/route': 'Route',
    '/role': 'Role',
    '/role/assign': 'Assign Role',
  },
  userActions: {
    profile: 'Profile',
    editPwd: 'Edit Password',
    logout: 'Logout',
    confirm: {
      title: 'Action confirm',
      ok: 'Sure',
      cancel: 'Cancel',
      content: 'Are you sure to logout?',
    },
  },
  buttons: {
    add: 'Add',
    edit: 'Edit',
    dele: 'Delete',
    search: 'Search',
    reset: 'Reset',
    submit: 'Submit',
  },
  tips: {
    autoGen: 'Auto generated by default',
  },
  deleConfirm: {
    title: 'Are you sure?',
    yes: 'Yes',
    cancel: 'No',
  },
  table: {
    addTime: 'Add Time',
    operation: 'Operation',
  },
  formTip: {
    input: 'Please input {name}!',
    select: 'Please select {name}!',
    confirmFail: "Those {name} didn't match. Try again.",
    account: 'Only numbers or letters are accepted!',
  },
  placeholder: {
    selector: 'Click to select',
    routeParent:
      'If not selected and Component empty，will create a parent route',
    search: 'Search by {title}',
  },
  admin: {
    login: 'Login',
    account: 'Account',
    name: 'User Name',
    email: 'Email',
    role: 'Role', //name of the type
    password: 'Password',
    newPwd: 'New Password', //修改密码时
    oldPwd: 'Current Password', //修改密码时
    confirm: 'Confirm', //修改密码时
    remember_me: 'Remember me',
    title: 'Title',
    staffNo: 'Staff No',
    disabled: 'Disabled',
    qualifyCount: 'Qualifications',
  },
  route: {
    pid: 'Parent',
    name: 'Name',
    path: 'Path',
    component: 'Component',
    sort: 'Sort',
    isMenu: 'Is Menu',
    icon: 'Icon',
  },
  role: {
    name: 'Name',
    ownRoutes: 'Owned Permissions',
    all: 'All',
    assign: 'Assign permissions',
    notifyDay: 'Notify day',
  },
}
